name: owlapy
channels:
  - defaults
  - conda-forge
dependencies:
  - pandas=1.2.3
  - sortedcontainers=2.3.0
  - owlready2=0.34
  - rdflib=6.0.2
  - parsimonious=0.8.1
  # testing
  - tox=3.23.0
  - tox-conda=0.7.1
  - pytest=6.2.2
  # docs
  - sphinx=3.5.3
  - sphinx_rtd_theme=0.5.1
  - myst-parser=0.13.5
  # # building
  - build=0.3.1.post1
  - pip=21.0.1
  - pip:
    # docs
    - sphinxext-autox==0.0.2
    - sphinx-theme==1.0
